#!/bin/bash
username="your-username-here"

# system
add_fstab_lines="yes"
fstab_lines="# add your fstab extra lines here to be appended"
add_crypttab_lines="yes"
crypttab_lines="# add your crypttab extra lines here to be appended"
fix_sudden_volume_spikes="yes"
enable_rpm_fusion_repos="yes"
#install_ms_fonts="yes"
improve_font_rendering="yes"

# drivers
#install_nvidia_340xx="yes"
virtualbox_guest_additions="yes"
install_qemu_spice_qxl="yes"

# extra
install_someonewhocares_hosts_file="yes"
install_multimedia_plugins="yes"
install_samba="yes"
samba_lines="# add your fstab extra lines here to be appended"
install_syncthing="yes"
install_firefox="yes"
install_google_chrome="yes"
install_vlc="yes"
install_clementine="yes"
install_libreoffice="yes"
install_virtualbox="yes"
install_qemu="yes"
install_qbittorrent="yes"
install_gimp="yes"
install_kdenlive="yes"
#install_steam="yes"
install_vmware_player="yes"
install_vmware_pro="no"

# development
#install_git="yes"
#install_gitkraken="yes"
#install_vscode="yes"
#install_allegro5="yes"
#install_arduino="yes"
#install_eclipse="yes"
#install_android_studio="yes"
#install_pycharm_community="yes"
#install_eyed3="yes"
#install_xlsxwriter="yes"
#install_nuitka="yes"
#install_kivy="yes"
#install_mysql_workbench="yes"
#install_lamp_server="yes"
#install_apache_tomcat="yes"
